const IconName = {
  REACT: 'react',
  HOME: 'util/home',
  MY_PAGE: 'util/my-page',
  VOUCHER: 'util/voucher',
  COMMUNITY: 'util/community',
  NOT_FOUND: 'not-found',
  LOGO: 'logo',
  LOGO2: 'logo2',
  TIGER: 'tiger',
  DOG: 'dog',
  CAT: 'cat',
  RABBIT: 'rabbit',
  SEAGULL: 'seagull',
  PERSON: 'util/person',
  MONEY: 'util/money',
  HEART_EMPTY: 'util/heart-empty',
  ARROW_BACK: 'util/arrow-back',
  CHAT_RECORD: 'home/chat-record',
  CHAT_RECORD_FOOTER: 'home/chat-record-footer',
  CHARACTER_CHANGE: 'home/character-change',
  NOTICE: 'home/notice',
} as const;

export default IconName;
