export const SPORTS_ICONS: Record<string, string> = {
  수영: '/icons/sports/swimming.svg',
  헬스: '/icons/sports/gym.svg',
  요가: '/icons/sports/yoga.svg',
  필라테스: '/icons/sports/pilates.svg',
  태권도: '/icons/sports/taekwondo.svg',
  배드민턴: '/icons/sports/badminton.svg',
  탁구: '/icons/sports/table-tennis.svg',
  테니스: '/icons/sports/tennis.svg',
  골프: '/icons/sports/golf.svg',
  클라이밍: '/icons/sports/climbing.svg',
  스쿼시: '/icons/sports/squash.svg',
  농구: '/icons/sports/basketball.svg',
  축구: '/icons/sports/soccer.svg',
  default: '/logo2.svg',
};
